name: shared_ui
description: Shared UI package for MuthoBazar
publish_to: 'none'
version: 0.1.0

resolution: workspace
environment:
  sdk: ^3.9.0

dependencies:
  flutter:
      sdk: flutter
  shared_core:
      path: ../shared_core

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.8

