name: shared_core
description: Shared core utilities for MuthoBazar
publish_to: 'none'
version: 0.1.0

resolution: workspace
environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^1.2.1
  flutter_image_compress: ^2.4.0
  path_provider: ^2.1.5
  shared_preferences: ^2.3.2
  flutter_local_notifications: ^21.0.0
  get_storage: ^2.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  shared_models:
    path: ../shared_models

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.8

