name: admin_web
description: MuthoBazar admin web application
publish_to: 'none'
version: 0.1.0+1

resolution: workspace
environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter



  file_picker: ^8.1.2
  cloud_functions: ^6.1.0
  shared_preferences: ^2.3.2
  intl: ^0.20.2

  cached_network_image: ^3.4.1
  cloud_firestore: ^6.1.3
  cupertino_icons: ^1.0.8
  firebase_auth: ^6.2.0
  firebase_core: ^4.5.0
  firebase_storage: ^13.1.0
  get: ^4.6.6

  shared_core:
    path: ../../packages/shared_core
  shared_models:
    path: ../../packages/shared_models
  shared_contracts:
    path: ../../packages/shared_contracts
  shared_repositories:
    path: ../../packages/shared_repositories
  shared_services:
    path: ../../packages/shared_services
  shared_ui:
    path: ../../packages/shared_ui
  shared_usecases:
    path: ../../packages/shared_usecases
  shared_workflows:
    path: ../../packages/shared_workflows

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  pubspec_dependency_sorter: ^1.0.5

flutter:
  uses-material-design: true

