"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.logAdminAction = exports.adminHardDeleteProduct = exports.adminSetProductEnabled = exports.adminRestoreProduct = exports.adminDeleteProduct = exports.adminUpdateProduct = exports.adminCreateProduct = exports.setBannerActiveState = exports.deleteBanner = exports.updateBanner = exports.createBanner = exports.setBrandActiveState = exports.deleteBrand = exports.updateBrand = exports.createBrand = exports.fixCategoryGroupSort = exports.reorderCategoryGroup = exports.setCategoryActiveState = exports.deleteCategory = exports.updateCategory = exports.createCategory = exports.onProductDeletedUpdateCategoryCount = exports.onProductUpdatedUpdateCategoryCount = exports.onProductCreatedUpdateCategoryCount = exports.checkPhoneAuthEligibility = void 0;
const app_1 = require("firebase-admin/app");
const options_1 = require("firebase-functions/v2/options");
(0, app_1.initializeApp)();
(0, options_1.setGlobalOptions)({
    region: "asia-south1",
});
var check_phone_auth_eligibility_1 = require("./auth/check-phone-auth-eligibility");
Object.defineProperty(exports, "checkPhoneAuthEligibility", { enumerable: true, get: function () { return check_phone_auth_eligibility_1.checkPhoneAuthEligibility; } });
var category_product_count_1 = require("./categories/category-product-count");
Object.defineProperty(exports, "onProductCreatedUpdateCategoryCount", { enumerable: true, get: function () { return category_product_count_1.onProductCreatedUpdateCategoryCount; } });
Object.defineProperty(exports, "onProductUpdatedUpdateCategoryCount", { enumerable: true, get: function () { return category_product_count_1.onProductUpdatedUpdateCategoryCount; } });
Object.defineProperty(exports, "onProductDeletedUpdateCategoryCount", { enumerable: true, get: function () { return category_product_count_1.onProductDeletedUpdateCategoryCount; } });
var create_category_1 = require("./categories/create-category");
Object.defineProperty(exports, "createCategory", { enumerable: true, get: function () { return create_category_1.createCategory; } });
var update_category_1 = require("./categories/update-category");
Object.defineProperty(exports, "updateCategory", { enumerable: true, get: function () { return update_category_1.updateCategory; } });
var delete_category_1 = require("./categories/delete-category");
Object.defineProperty(exports, "deleteCategory", { enumerable: true, get: function () { return delete_category_1.deleteCategory; } });
var set_category_active_state_1 = require("./categories/set-category-active-state");
Object.defineProperty(exports, "setCategoryActiveState", { enumerable: true, get: function () { return set_category_active_state_1.setCategoryActiveState; } });
var reorder_categories_1 = require("./categories/reorder-categories");
Object.defineProperty(exports, "reorderCategoryGroup", { enumerable: true, get: function () { return reorder_categories_1.reorderCategoryGroup; } });
var fix_category_group_sort_1 = require("./categories/fix-category-group-sort");
Object.defineProperty(exports, "fixCategoryGroupSort", { enumerable: true, get: function () { return fix_category_group_sort_1.fixCategoryGroupSort; } });
var create_brand_1 = require("./brands/create-brand");
Object.defineProperty(exports, "createBrand", { enumerable: true, get: function () { return create_brand_1.createBrand; } });
var update_brand_1 = require("./brands/update-brand");
Object.defineProperty(exports, "updateBrand", { enumerable: true, get: function () { return update_brand_1.updateBrand; } });
var delete_brand_1 = require("./brands/delete-brand");
Object.defineProperty(exports, "deleteBrand", { enumerable: true, get: function () { return delete_brand_1.deleteBrand; } });
var set_brand_active_state_1 = require("./brands/set-brand-active-state");
Object.defineProperty(exports, "setBrandActiveState", { enumerable: true, get: function () { return set_brand_active_state_1.setBrandActiveState; } });
var create_banner_1 = require("./banners/create-banner");
Object.defineProperty(exports, "createBanner", { enumerable: true, get: function () { return create_banner_1.createBanner; } });
var update_banner_1 = require("./banners/update-banner");
Object.defineProperty(exports, "updateBanner", { enumerable: true, get: function () { return update_banner_1.updateBanner; } });
var delete_banner_1 = require("./banners/delete-banner");
Object.defineProperty(exports, "deleteBanner", { enumerable: true, get: function () { return delete_banner_1.deleteBanner; } });
var set_banner_active_state_1 = require("./banners/set-banner-active-state");
Object.defineProperty(exports, "setBannerActiveState", { enumerable: true, get: function () { return set_banner_active_state_1.setBannerActiveState; } });
var admin_create_product_1 = require("./products/admin_create_product");
Object.defineProperty(exports, "adminCreateProduct", { enumerable: true, get: function () { return admin_create_product_1.adminCreateProduct; } });
var admin_update_product_1 = require("./products/admin_update_product");
Object.defineProperty(exports, "adminUpdateProduct", { enumerable: true, get: function () { return admin_update_product_1.adminUpdateProduct; } });
var admin_delete_product_1 = require("./products/admin_delete_product");
Object.defineProperty(exports, "adminDeleteProduct", { enumerable: true, get: function () { return admin_delete_product_1.adminDeleteProduct; } });
var admin_restore_product_1 = require("./products/admin_restore_product");
Object.defineProperty(exports, "adminRestoreProduct", { enumerable: true, get: function () { return admin_restore_product_1.adminRestoreProduct; } });
var admin_set_product_enabled_1 = require("./products/admin_set_product_enabled");
Object.defineProperty(exports, "adminSetProductEnabled", { enumerable: true, get: function () { return admin_set_product_enabled_1.adminSetProductEnabled; } });
var admin_hard_delete_product_1 = require("./products/admin_hard_delete_product");
Object.defineProperty(exports, "adminHardDeleteProduct", { enumerable: true, get: function () { return admin_hard_delete_product_1.adminHardDeleteProduct; } });
var log_admin_action_1 = require("./admin/log-admin-action");
Object.defineProperty(exports, "logAdminAction", { enumerable: true, get: function () { return log_admin_action_1.logAdminAction; } });
