"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.fixCategoryGroupSort = exports.reorderCategoryGroup = exports.onProductDeletedUpdateCategoryCount = exports.onProductUpdatedUpdateCategoryCount = exports.onProductCreatedUpdateCategoryCount = exports.checkPhoneAuthEligibility = void 0;
const app_1 = require("firebase-admin/app");
(0, app_1.initializeApp)();
var check_phone_auth_eligibility_1 = require("./check-phone-auth-eligibility");
Object.defineProperty(exports, "checkPhoneAuthEligibility", { enumerable: true, get: function () { return check_phone_auth_eligibility_1.checkPhoneAuthEligibility; } });
var category_product_count_1 = require("./category-product-count");
Object.defineProperty(exports, "onProductCreatedUpdateCategoryCount", { enumerable: true, get: function () { return category_product_count_1.onProductCreatedUpdateCategoryCount; } });
Object.defineProperty(exports, "onProductUpdatedUpdateCategoryCount", { enumerable: true, get: function () { return category_product_count_1.onProductUpdatedUpdateCategoryCount; } });
Object.defineProperty(exports, "onProductDeletedUpdateCategoryCount", { enumerable: true, get: function () { return category_product_count_1.onProductDeletedUpdateCategoryCount; } });
var reorder_categories_1 = require("./categories/reorder-categories");
Object.defineProperty(exports, "reorderCategoryGroup", { enumerable: true, get: function () { return reorder_categories_1.reorderCategoryGroup; } });
var fix_category_group_sort_1 = require("./categories/fix-category-group-sort");
Object.defineProperty(exports, "fixCategoryGroupSort", { enumerable: true, get: function () { return fix_category_group_sort_1.fixCategoryGroupSort; } });
