// MuthoBazar Advanced Product Card Design Studio
// Patch 2B element/variant catalog.
//
// Purpose:
// - Expands the left drawer to a much larger starter catalog.
// - Keeps the drawer grouped by expandable sections.
// - Each section exposes concrete draggable variants.
// - Card variants patch the document layout/palette instead of creating nodes.
//
// Note:
// - This patch intentionally expands the starter catalog beyond the earlier
//   minimal set so the studio can grow toward the full advanced tool.

import 'mb_advanced_card_design_document.dart';

class MBAdvancedElementVariant {
  const MBAdvancedElementVariant({
    required this.id,
    required this.groupId,
    required this.elementType,
    required this.title,
    required this.description,
    required this.binding,
    required this.defaultPosition,
    required this.defaultSize,
    required this.defaultStyle,
    this.cardLayoutPatch = const <String, dynamic>{},
    this.cardPalettePatch = const <String, dynamic>{},
  });

  final String id;
  final String groupId;
  final String elementType;
  final String title;
  final String description;
  final String binding;
  final MBAdvancedDesignNodePosition defaultPosition;
  final MBAdvancedDesignNodeSize defaultSize;
  final Map<String, dynamic> defaultStyle;
  final Map<String, dynamic> cardLayoutPatch;
  final Map<String, dynamic> cardPalettePatch;

  bool get isCardVariant => elementType == 'card';
}

class MBAdvancedElementGroup {
  const MBAdvancedElementGroup({
    required this.id,
    required this.title,
    required this.subtitle,
    required this.variants,
  });

  final String id;
  final String title;
  final String subtitle;
  final List<MBAdvancedElementVariant> variants;
}

class MBAdvancedElementCatalog {
  const MBAdvancedElementCatalog._();

  static List<MBAdvancedElementGroup> groups() {
    return const <MBAdvancedElementGroup>[
      MBAdvancedElementGroup(
        id: 'card',
        title: 'Card',
        subtitle: 'Card body, layout family and palette',
        variants: <MBAdvancedElementVariant>[
          MBAdvancedElementVariant(
            id: 'card_orange_gradient',
            groupId: 'card',
            elementType: 'card',
            title: 'Orange poster',
            description: 'Tall orange hero card',
            binding: 'card',
            defaultPosition: MBAdvancedDesignNodePosition(x: 0.5, y: 0.5),
            defaultSize: MBAdvancedDesignNodeSize(width: 240, height: 380),
            defaultStyle: <String, dynamic>{},
            cardLayoutPatch: <String, dynamic>{
              'cardWidth': 240.0,
              'cardHeight': 380.0,
              'borderRadius': 28.0,
            },
            cardPalettePatch: <String, dynamic>{
              'presetId': 'orangeGradient',
              'backgroundHex': '#FF6500',
              'backgroundHex2': '#FF9A3D',
              'surfaceHex': '#FFFFFF',
            },
          ),
          MBAdvancedElementVariant(
            id: 'card_white_soft',
            groupId: 'card',
            elementType: 'card',
            title: 'White soft',
            description: 'Soft white floating card',
            binding: 'card',
            defaultPosition: MBAdvancedDesignNodePosition(x: 0.5, y: 0.5),
            defaultSize: MBAdvancedDesignNodeSize(width: 240, height: 340),
            defaultStyle: <String, dynamic>{},
            cardLayoutPatch: <String, dynamic>{
              'cardWidth': 240.0,
              'cardHeight': 340.0,
              'borderRadius': 24.0,
            },
            cardPalettePatch: <String, dynamic>{
              'presetId': 'whiteSoft',
              'backgroundHex': '#FFFFFF',
              'backgroundHex2': '#FFF6EF',
              'surfaceHex': '#FFE8D4',
            },
          ),
          MBAdvancedElementVariant(
            id: 'card_compact_row',
            groupId: 'card',
            elementType: 'card',
            title: 'Compact row',
            description: 'Wide row card',
            binding: 'card',
            defaultPosition: MBAdvancedDesignNodePosition(x: 0.5, y: 0.5),
            defaultSize: MBAdvancedDesignNodeSize(width: 330, height: 170),
            defaultStyle: <String, dynamic>{},
            cardLayoutPatch: <String, dynamic>{
              'cardWidth': 330.0,
              'cardHeight': 170.0,
              'borderRadius': 24.0,
            },
            cardPalettePatch: <String, dynamic>{
              'presetId': 'compactOrange',
              'backgroundHex': '#FFF6EF',
              'backgroundHex2': '#FFE5D1',
              'surfaceHex': '#FFFFFF',
            },
          ),
        ],
      ),
      MBAdvancedElementGroup(
        id: 'title',
        title: 'Title',
        subtitle: 'Main product title styles',
        variants: <MBAdvancedElementVariant>[
          MBAdvancedElementVariant(
            id: 'title_text',
            groupId: 'title',
            elementType: 'title',
            title: 'Text',
            description: 'Main title text',
            binding: 'product.titleEn',
            defaultPosition: MBAdvancedDesignNodePosition(x: 0.20, y: 0.12, z: 20),
            defaultSize: MBAdvancedDesignNodeSize(width: 180, height: 44),
            defaultStyle: <String, dynamic>{
              'textColorHex': '#FFFFFF',
              'fontSize': 20.0,
              'fontWeight': 'w900',
              'textAlign': 'left',
            },
          ),
          MBAdvancedElementVariant(
            id: 'title_soft_chip',
            groupId: 'title',
            elementType: 'title',
            title: 'Soft chip',
            description: 'Chip title',
            binding: 'product.titleEn',
            defaultPosition: MBAdvancedDesignNodePosition(x: 0.30, y: 0.12, z: 22),
            defaultSize: MBAdvancedDesignNodeSize(width: 160, height: 32),
            defaultStyle: <String, dynamic>{
              'backgroundHex': '#FFFFFF',
              'textColorHex': '#FF6500',
              'fontSize': 13.0,
              'fontWeight': 'w900',
              'borderRadius': 999.0,
            },
          ),
        ],
      ),
      MBAdvancedElementGroup(
        id: 'subtitle',
        title: 'Subtitle',
        subtitle: 'Supporting text block variants',
        variants: <MBAdvancedElementVariant>[
          MBAdvancedElementVariant(
            id: 'subtitle_text',
            groupId: 'subtitle',
            elementType: 'subtitle',
            title: 'Text',
            description: 'Supporting subtitle',
            binding: 'product.shortDescriptionEn',
            defaultPosition: MBAdvancedDesignNodePosition(x: 0.22, y: 0.22, z: 20),
            defaultSize: MBAdvancedDesignNodeSize(width: 180, height: 42),
            defaultStyle: <String, dynamic>{
              'textColorHex': '#FFF4E8',
              'fontSize': 11.0,
              'fontWeight': 'w600',
              'textAlign': 'left',
            },
          ),
          MBAdvancedElementVariant(
            id: 'subtitle_chip',
            groupId: 'subtitle',
            elementType: 'subtitle',
            title: 'Chip',
            description: 'Subtitle in chip',
            binding: 'product.shortDescriptionEn',
            defaultPosition: MBAdvancedDesignNodePosition(x: 0.30, y: 0.22, z: 21),
            defaultSize: MBAdvancedDesignNodeSize(width: 152, height: 28),
            defaultStyle: <String, dynamic>{
              'backgroundHex': '#FFF6EF',
              'textColorHex': '#C25500',
              'fontSize': 10.0,
              'fontWeight': 'w800',
              'borderRadius': 999.0,
            },
          ),
        ],
      ),
      MBAdvancedElementGroup(
        id: 'brand',
        title: 'Brand',
        subtitle: 'Brand name or pill',
        variants: <MBAdvancedElementVariant>[
          MBAdvancedElementVariant(
            id: 'brand_text',
            groupId: 'brand',
            elementType: 'brand',
            title: 'Brand text',
            description: 'Brand label',
            binding: 'product.brandName',
            defaultPosition: MBAdvancedDesignNodePosition(x: 0.18, y: 0.06, z: 24),
            defaultSize: MBAdvancedDesignNodeSize(width: 120, height: 22),
            defaultStyle: <String, dynamic>{
              'textColorHex': '#FFF0E4',
              'fontSize': 11.0,
              'fontWeight': 'w700',
              'text': 'Fresh Farms',
            },
          ),
          MBAdvancedElementVariant(
            id: 'brand_chip',
            groupId: 'brand',
            elementType: 'brand',
            title: 'Brand chip',
            description: 'Rounded brand chip',
            binding: 'product.brandName',
            defaultPosition: MBAdvancedDesignNodePosition(x: 0.24, y: 0.06, z: 24),
            defaultSize: MBAdvancedDesignNodeSize(width: 108, height: 24),
            defaultStyle: <String, dynamic>{
              'backgroundHex': '#FFFFFF',
              'textColorHex': '#FF6500',
              'fontSize': 10.0,
              'fontWeight': 'w800',
              'borderRadius': 999.0,
              'text': 'Fresh Farms',
            },
          ),
        ],
      ),
      MBAdvancedElementGroup(
        id: 'category',
        title: 'Category',
        subtitle: 'Category tag variations',
        variants: <MBAdvancedElementVariant>[
          MBAdvancedElementVariant(
            id: 'category_text',
            groupId: 'category',
            elementType: 'category',
            title: 'Category text',
            description: 'Category plain text',
            binding: 'product.categoryName',
            defaultPosition: MBAdvancedDesignNodePosition(x: 0.18, y: 0.28, z: 22),
            defaultSize: MBAdvancedDesignNodeSize(width: 130, height: 22),
            defaultStyle: <String, dynamic>{
              'textColorHex': '#FFFFFF',
              'fontSize': 10.5,
              'fontWeight': 'w700',
              'text': 'Vegetables',
            },
          ),
          MBAdvancedElementVariant(
            id: 'category_chip',
            groupId: 'category',
            elementType: 'category',
            title: 'Category chip',
            description: 'Category chip tag',
            binding: 'product.categoryName',
            defaultPosition: MBAdvancedDesignNodePosition(x: 0.30, y: 0.28, z: 22),
            defaultSize: MBAdvancedDesignNodeSize(width: 112, height: 24),
            defaultStyle: <String, dynamic>{
              'backgroundHex': '#FFFFFF',
              'textColorHex': '#D85B00',
              'fontSize': 10.0,
              'fontWeight': 'w800',
              'borderRadius': 999.0,
              'text': 'Vegetables',
            },
          ),
        ],
      ),
      MBAdvancedElementGroup(
        id: 'media',
        title: 'Media',
        subtitle: 'Main product image styles',
        variants: <MBAdvancedElementVariant>[
          MBAdvancedElementVariant(
            id: 'media_circle_ring',
            groupId: 'media',
            elementType: 'media',
            title: 'Circle',
            description: 'Circular image',
            binding: 'product.thumbnailUrl',
            defaultPosition: MBAdvancedDesignNodePosition(x: 0.50, y: 0.52, z: 30),
            defaultSize: MBAdvancedDesignNodeSize(width: 156, height: 156),
            defaultStyle: <String, dynamic>{
              'borderHex': '#FFFFFF',
              'ringWidth': 6.0,
              'borderRadius': 999.0,
            },
          ),
          MBAdvancedElementVariant(
            id: 'media_rounded_rect',
            groupId: 'media',
            elementType: 'media',
            title: 'Rounded',
            description: 'Rounded media block',
            binding: 'product.thumbnailUrl',
            defaultPosition: MBAdvancedDesignNodePosition(x: 0.50, y: 0.52, z: 30),
            defaultSize: MBAdvancedDesignNodeSize(width: 160, height: 132),
            defaultStyle: <String, dynamic>{
              'borderHex': '#FFFFFF',
              'ringWidth': 4.0,
              'borderRadius': 26.0,
            },
          ),
        ],
      ),
      MBAdvancedElementGroup(
        id: 'price',
        title: 'Price',
        subtitle: 'Selling price styles',
        variants: <MBAdvancedElementVariant>[
          MBAdvancedElementVariant(
            id: 'price_circle',
            groupId: 'price',
            elementType: 'price',
            title: 'Circle price',
            description: 'Round price bubble',
            binding: 'product.finalPrice',
            defaultPosition: MBAdvancedDesignNodePosition(x: 0.84, y: 0.16, z: 40),
            defaultSize: MBAdvancedDesignNodeSize(width: 68, height: 68),
            defaultStyle: <String, dynamic>{
              'backgroundHex': '#FFFFFF',
              'textColorHex': '#FF6500',
              'fontSize': 14.0,
              'fontWeight': 'w900',
              'borderRadius': 999.0,
            },
          ),
          MBAdvancedElementVariant(
            id: 'price_pill',
            groupId: 'price',
            elementType: 'price',
            title: 'Pill price',
            description: 'Horizontal price pill',
            binding: 'product.finalPrice',
            defaultPosition: MBAdvancedDesignNodePosition(x: 0.72, y: 0.82, z: 40),
            defaultSize: MBAdvancedDesignNodeSize(width: 112, height: 32),
            defaultStyle: <String, dynamic>{
              'backgroundHex': '#FFFFFF',
              'textColorHex': '#FF6500',
              'fontSize': 13.0,
              'fontWeight': 'w900',
              'borderRadius': 999.0,
            },
          ),
        ],
      ),
      MBAdvancedElementGroup(
        id: 'mrp',
        title: 'MRP / Old price',
        subtitle: 'Original price display',
        variants: <MBAdvancedElementVariant>[
          MBAdvancedElementVariant(
            id: 'mrp_text',
            groupId: 'mrp',
            elementType: 'mrp',
            title: 'MRP text',
            description: 'Original price text',
            binding: 'product.price',
            defaultPosition: MBAdvancedDesignNodePosition(x: 0.28, y: 0.80, z: 34),
            defaultSize: MBAdvancedDesignNodeSize(width: 94, height: 22),
            defaultStyle: <String, dynamic>{
              'textColorHex': '#FBE4D5',
              'fontSize': 10.0,
              'fontWeight': 'w700',
              'prefixText': 'MRP ',
              'decoration': 'lineThrough',
            },
          ),
          MBAdvancedElementVariant(
            id: 'mrp_chip',
            groupId: 'mrp',
            elementType: 'mrp',
            title: 'MRP chip',
            description: 'Original price pill',
            binding: 'product.price',
            defaultPosition: MBAdvancedDesignNodePosition(x: 0.30, y: 0.80, z: 34),
            defaultSize: MBAdvancedDesignNodeSize(width: 106, height: 24),
            defaultStyle: <String, dynamic>{
              'backgroundHex': '#FBDCC8',
              'textColorHex': '#9E4700',
              'fontSize': 10.0,
              'fontWeight': 'w800',
              'borderRadius': 999.0,
              'prefixText': 'MRP ',
            },
          ),
        ],
      ),
      MBAdvancedElementGroup(
        id: 'discount',
        title: 'Discount',
        subtitle: 'Save %, off, discount labels',
        variants: <MBAdvancedElementVariant>[
          MBAdvancedElementVariant(
            id: 'discount_badge',
            groupId: 'discount',
            elementType: 'discount',
            title: 'Discount badge',
            description: 'Percentage save chip',
            binding: 'static.discount',
            defaultPosition: MBAdvancedDesignNodePosition(x: 0.76, y: 0.28, z: 38),
            defaultSize: MBAdvancedDesignNodeSize(width: 76, height: 28),
            defaultStyle: <String, dynamic>{
              'backgroundHex': '#151922',
              'textColorHex': '#FFFFFF',
              'fontSize': 11.0,
              'fontWeight': 'w900',
              'borderRadius': 999.0,
              'label': '25% OFF',
            },
          ),
          MBAdvancedElementVariant(
            id: 'discount_corner',
            groupId: 'discount',
            elementType: 'discount',
            title: 'Discount pill',
            description: 'Warm discount chip',
            binding: 'static.discount',
            defaultPosition: MBAdvancedDesignNodePosition(x: 0.78, y: 0.30, z: 38),
            defaultSize: MBAdvancedDesignNodeSize(width: 84, height: 30),
            defaultStyle: <String, dynamic>{
              'backgroundHex': '#FFE9D5',
              'textColorHex': '#CB5300',
              'fontSize': 11.0,
              'fontWeight': 'w900',
              'borderRadius': 999.0,
              'label': 'SAVE 25%',
            },
          ),
        ],
      ),
      MBAdvancedElementGroup(
        id: 'cta',
        title: 'CTA',
        subtitle: 'Call-to-action button variants',
        variants: <MBAdvancedElementVariant>[
          MBAdvancedElementVariant(
            id: 'cta_buy',
            groupId: 'cta',
            elementType: 'cta',
            title: 'Buy pill',
            description: 'Rounded buy button',
            binding: 'action.buy',
            defaultPosition: MBAdvancedDesignNodePosition(x: 0.76, y: 0.92, z: 44),
            defaultSize: MBAdvancedDesignNodeSize(width: 86, height: 34),
            defaultStyle: <String, dynamic>{
              'backgroundHex': '#151922',
              'textColorHex': '#FFFFFF',
              'fontSize': 12.0,
              'fontWeight': 'w900',
              'borderRadius': 999.0,
              'label': 'Buy',
            },
          ),
          MBAdvancedElementVariant(
            id: 'cta_outline',
            groupId: 'cta',
            elementType: 'cta',
            title: 'Outline',
            description: 'Outlined CTA',
            binding: 'action.details',
            defaultPosition: MBAdvancedDesignNodePosition(x: 0.72, y: 0.92, z: 44),
            defaultSize: MBAdvancedDesignNodeSize(width: 96, height: 34),
            defaultStyle: <String, dynamic>{
              'backgroundHex': '#FFFFFF',
              'textColorHex': '#FF6500',
              'borderHex': '#FF6500',
              'fontSize': 12.0,
              'fontWeight': 'w900',
              'borderRadius': 999.0,
              'label': 'View',
            },
          ),
        ],
      ),
      MBAdvancedElementGroup(
        id: 'badge',
        title: 'Badge',
        subtitle: 'Promo, hot, new, featured badges',
        variants: <MBAdvancedElementVariant>[
          MBAdvancedElementVariant(
            id: 'badge_hot',
            groupId: 'badge',
            elementType: 'badge',
            title: 'Soft badge',
            description: 'Promo chip',
            binding: 'static.badge',
            defaultPosition: MBAdvancedDesignNodePosition(x: 0.22, y: 0.90, z: 46),
            defaultSize: MBAdvancedDesignNodeSize(width: 84, height: 28),
            defaultStyle: <String, dynamic>{
              'backgroundHex': '#FFFFFF',
              'textColorHex': '#FF6500',
              'fontSize': 11.0,
              'fontWeight': 'w900',
              'borderRadius': 999.0,
              'label': 'HOT',
            },
          ),
          MBAdvancedElementVariant(
            id: 'badge_new',
            groupId: 'badge',
            elementType: 'badge',
            title: 'Dark badge',
            description: 'Dark chip',
            binding: 'static.badge',
            defaultPosition: MBAdvancedDesignNodePosition(x: 0.22, y: 0.90, z: 46),
            defaultSize: MBAdvancedDesignNodeSize(width: 84, height: 28),
            defaultStyle: <String, dynamic>{
              'backgroundHex': '#151922',
              'textColorHex': '#FFFFFF',
              'fontSize': 11.0,
              'fontWeight': 'w900',
              'borderRadius': 999.0,
              'label': 'NEW',
            },
          ),
        ],
      ),
      MBAdvancedElementGroup(
        id: 'timer',
        title: 'Timer',
        subtitle: 'Flash sale or countdown timer styles',
        variants: <MBAdvancedElementVariant>[
          MBAdvancedElementVariant(
            id: 'timer_chip',
            groupId: 'timer',
            elementType: 'timer',
            title: 'Timer chip',
            description: 'Rounded timer chip',
            binding: 'static.timer',
            defaultPosition: MBAdvancedDesignNodePosition(x: 0.28, y: 0.76, z: 36),
            defaultSize: MBAdvancedDesignNodeSize(width: 104, height: 30),
            defaultStyle: <String, dynamic>{
              'backgroundHex': '#FFFFFF',
              'textColorHex': '#FF6500',
              'fontSize': 11.0,
              'fontWeight': 'w900',
              'borderRadius': 16.0,
              'label': '02:15:08',
            },
          ),
          MBAdvancedElementVariant(
            id: 'timer_dark',
            groupId: 'timer',
            elementType: 'timer',
            title: 'Dark timer',
            description: 'Dark timer pill',
            binding: 'static.timer',
            defaultPosition: MBAdvancedDesignNodePosition(x: 0.30, y: 0.76, z: 36),
            defaultSize: MBAdvancedDesignNodeSize(width: 112, height: 30),
            defaultStyle: <String, dynamic>{
              'backgroundHex': '#1A2030',
              'textColorHex': '#FFFFFF',
              'fontSize': 11.0,
              'fontWeight': 'w900',
              'borderRadius': 16.0,
              'label': '02:15:08',
            },
          ),
        ],
      ),
      MBAdvancedElementGroup(
        id: 'rating',
        title: 'Rating',
        subtitle: 'Star rating and review indicator',
        variants: <MBAdvancedElementVariant>[
          MBAdvancedElementVariant(
            id: 'rating_star',
            groupId: 'rating',
            elementType: 'rating',
            title: 'Star rating',
            description: 'Star + score',
            binding: 'static.rating',
            defaultPosition: MBAdvancedDesignNodePosition(x: 0.26, y: 0.32, z: 26),
            defaultSize: MBAdvancedDesignNodeSize(width: 86, height: 24),
            defaultStyle: <String, dynamic>{
              'backgroundHex': '#FFFFFF',
              'textColorHex': '#FF6500',
              'fontSize': 10.5,
              'fontWeight': 'w800',
              'borderRadius': 999.0,
              'label': '★ 4.8',
            },
          ),
          MBAdvancedElementVariant(
            id: 'rating_plain',
            groupId: 'rating',
            elementType: 'rating',
            title: 'Plain rating',
            description: 'Simple rating text',
            binding: 'static.rating',
            defaultPosition: MBAdvancedDesignNodePosition(x: 0.26, y: 0.32, z: 26),
            defaultSize: MBAdvancedDesignNodeSize(width: 64, height: 20),
            defaultStyle: <String, dynamic>{
              'textColorHex': '#FFFFFF',
              'fontSize': 10.5,
              'fontWeight': 'w800',
              'label': '★ 4.8',
            },
          ),
        ],
      ),
      MBAdvancedElementGroup(
        id: 'stock',
        title: 'Stock',
        subtitle: 'Stock and availability states',
        variants: <MBAdvancedElementVariant>[
          MBAdvancedElementVariant(
            id: 'stock_available',
            groupId: 'stock',
            elementType: 'stock',
            title: 'In stock',
            description: 'Available badge',
            binding: 'static.stock',
            defaultPosition: MBAdvancedDesignNodePosition(x: 0.74, y: 0.34, z: 37),
            defaultSize: MBAdvancedDesignNodeSize(width: 86, height: 26),
            defaultStyle: <String, dynamic>{
              'backgroundHex': '#EAFBF0',
              'textColorHex': '#12803B',
              'fontSize': 10.0,
              'fontWeight': 'w800',
              'borderRadius': 999.0,
              'label': 'In stock',
            },
          ),
          MBAdvancedElementVariant(
            id: 'stock_low',
            groupId: 'stock',
            elementType: 'stock',
            title: 'Low stock',
            description: 'Urgency stock badge',
            binding: 'static.stock',
            defaultPosition: MBAdvancedDesignNodePosition(x: 0.74, y: 0.34, z: 37),
            defaultSize: MBAdvancedDesignNodeSize(width: 92, height: 26),
            defaultStyle: <String, dynamic>{
              'backgroundHex': '#FFF3E9',
              'textColorHex': '#E06E00',
              'fontSize': 10.0,
              'fontWeight': 'w800',
              'borderRadius': 999.0,
              'label': 'Low stock',
            },
          ),
        ],
      ),
      MBAdvancedElementGroup(
        id: 'delivery',
        title: 'Delivery',
        subtitle: 'Delivery or shipping note',
        variants: <MBAdvancedElementVariant>[
          MBAdvancedElementVariant(
            id: 'delivery_text',
            groupId: 'delivery',
            elementType: 'delivery',
            title: 'Delivery text',
            description: 'Shipping info',
            binding: 'static.delivery',
            defaultPosition: MBAdvancedDesignNodePosition(x: 0.35, y: 0.88, z: 40),
            defaultSize: MBAdvancedDesignNodeSize(width: 112, height: 24),
            defaultStyle: <String, dynamic>{
              'textColorHex': '#FFFFFF',
              'fontSize': 10.5,
              'fontWeight': 'w800',
              'label': 'Fast delivery',
            },
          ),
          MBAdvancedElementVariant(
            id: 'delivery_chip',
            groupId: 'delivery',
            elementType: 'delivery',
            title: 'Delivery chip',
            description: 'Delivery pill',
            binding: 'static.delivery',
            defaultPosition: MBAdvancedDesignNodePosition(x: 0.33, y: 0.88, z: 40),
            defaultSize: MBAdvancedDesignNodeSize(width: 120, height: 28),
            defaultStyle: <String, dynamic>{
              'backgroundHex': '#FFFFFF',
              'textColorHex': '#FF6500',
              'fontSize': 10.5,
              'fontWeight': 'w900',
              'borderRadius': 999.0,
              'label': 'Fast delivery',
            },
          ),
        ],
      ),
      MBAdvancedElementGroup(
        id: 'unit',
        title: 'Unit',
        subtitle: 'Weight, size, pcs, pack unit',
        variants: <MBAdvancedElementVariant>[
          MBAdvancedElementVariant(
            id: 'unit_text',
            groupId: 'unit',
            elementType: 'unit',
            title: 'Unit text',
            description: 'Weight text',
            binding: 'static.unit',
            defaultPosition: MBAdvancedDesignNodePosition(x: 0.22, y: 0.36, z: 25),
            defaultSize: MBAdvancedDesignNodeSize(width: 72, height: 22),
            defaultStyle: <String, dynamic>{
              'textColorHex': '#FFFFFF',
              'fontSize': 10.5,
              'fontWeight': 'w700',
              'label': '500 g',
            },
          ),
          MBAdvancedElementVariant(
            id: 'unit_chip',
            groupId: 'unit',
            elementType: 'unit',
            title: 'Unit chip',
            description: 'Rounded unit tag',
            binding: 'static.unit',
            defaultPosition: MBAdvancedDesignNodePosition(x: 0.24, y: 0.36, z: 25),
            defaultSize: MBAdvancedDesignNodeSize(width: 74, height: 24),
            defaultStyle: <String, dynamic>{
              'backgroundHex': '#FFFFFF',
              'textColorHex': '#FF6500',
              'fontSize': 10.0,
              'fontWeight': 'w800',
              'borderRadius': 999.0,
              'label': '500 g',
            },
          ),
        ],
      ),
      MBAdvancedElementGroup(
        id: 'feature',
        title: 'Feature',
        subtitle: 'USP or feature highlight',
        variants: <MBAdvancedElementVariant>[
          MBAdvancedElementVariant(
            id: 'feature_text',
            groupId: 'feature',
            elementType: 'feature',
            title: 'Feature text',
            description: 'One USP line',
            binding: 'static.feature',
            defaultPosition: MBAdvancedDesignNodePosition(x: 0.32, y: 0.40, z: 26),
            defaultSize: MBAdvancedDesignNodeSize(width: 140, height: 22),
            defaultStyle: <String, dynamic>{
              'textColorHex': '#FFF2E5',
              'fontSize': 10.0,
              'fontWeight': 'w700',
              'label': 'Farm fresh',
            },
          ),
          MBAdvancedElementVariant(
            id: 'feature_chip',
            groupId: 'feature',
            elementType: 'feature',
            title: 'Feature chip',
            description: 'Feature badge',
            binding: 'static.feature',
            defaultPosition: MBAdvancedDesignNodePosition(x: 0.34, y: 0.40, z: 26),
            defaultSize: MBAdvancedDesignNodeSize(width: 108, height: 26),
            defaultStyle: <String, dynamic>{
              'backgroundHex': '#FFFFFF',
              'textColorHex': '#FF6500',
              'fontSize': 10.0,
              'fontWeight': 'w800',
              'borderRadius': 999.0,
              'label': 'Farm fresh',
            },
          ),
        ],
      ),
      MBAdvancedElementGroup(
        id: 'wishlist',
        title: 'Wishlist',
        subtitle: 'Heart or favourite actions',
        variants: <MBAdvancedElementVariant>[
          MBAdvancedElementVariant(
            id: 'wishlist_heart',
            groupId: 'wishlist',
            elementType: 'wishlist',
            title: 'Heart icon',
            description: 'Heart action',
            binding: 'action.wishlist',
            defaultPosition: MBAdvancedDesignNodePosition(x: 0.86, y: 0.08, z: 42),
            defaultSize: MBAdvancedDesignNodeSize(width: 30, height: 30),
            defaultStyle: <String, dynamic>{
              'backgroundHex': '#FFFFFF',
              'textColorHex': '#FF6500',
              'fontSize': 16.0,
              'fontWeight': 'w900',
              'borderRadius': 999.0,
              'label': '♡',
            },
          ),
          MBAdvancedElementVariant(
            id: 'wishlist_filled',
            groupId: 'wishlist',
            elementType: 'wishlist',
            title: 'Filled heart',
            description: 'Filled favourite',
            binding: 'action.wishlist',
            defaultPosition: MBAdvancedDesignNodePosition(x: 0.86, y: 0.08, z: 42),
            defaultSize: MBAdvancedDesignNodeSize(width: 30, height: 30),
            defaultStyle: <String, dynamic>{
              'backgroundHex': '#FFFFFF',
              'textColorHex': '#FF4A4A',
              'fontSize': 16.0,
              'fontWeight': 'w900',
              'borderRadius': 999.0,
              'label': '♥',
            },
          ),
        ],
      ),
      MBAdvancedElementGroup(
        id: 'icon',
        title: 'Icon',
        subtitle: 'Small generic icon chip',
        variants: <MBAdvancedElementVariant>[
          MBAdvancedElementVariant(
            id: 'icon_star',
            groupId: 'icon',
            elementType: 'icon',
            title: 'Star icon',
            description: 'Star badge',
            binding: 'static.icon',
            defaultPosition: MBAdvancedDesignNodePosition(x: 0.52, y: 0.76, z: 36),
            defaultSize: MBAdvancedDesignNodeSize(width: 24, height: 24),
            defaultStyle: <String, dynamic>{
              'backgroundHex': '#FFFFFF',
              'textColorHex': '#FF6500',
              'fontSize': 14.0,
              'fontWeight': 'w900',
              'borderRadius': 999.0,
              'label': '✪',
            },
          ),
          MBAdvancedElementVariant(
            id: 'icon_flash',
            groupId: 'icon',
            elementType: 'icon',
            title: 'Flash icon',
            description: 'Flash marker',
            binding: 'static.icon',
            defaultPosition: MBAdvancedDesignNodePosition(x: 0.52, y: 0.76, z: 36),
            defaultSize: MBAdvancedDesignNodeSize(width: 24, height: 24),
            defaultStyle: <String, dynamic>{
              'backgroundHex': '#FFFFFF',
              'textColorHex': '#FF6500',
              'fontSize': 14.0,
              'fontWeight': 'w900',
              'borderRadius': 999.0,
              'label': '⚡',
            },
          ),
        ],
      ),
      MBAdvancedElementGroup(
        id: 'quantity',
        title: 'Quantity',
        subtitle: 'Qty controller or pack counter',
        variants: <MBAdvancedElementVariant>[
          MBAdvancedElementVariant(
            id: 'quantity_stepper',
            groupId: 'quantity',
            elementType: 'quantity',
            title: 'Qty stepper',
            description: 'Minus/plus quantity',
            binding: 'static.quantity',
            defaultPosition: MBAdvancedDesignNodePosition(x: 0.66, y: 0.88, z: 43),
            defaultSize: MBAdvancedDesignNodeSize(width: 88, height: 28),
            defaultStyle: <String, dynamic>{
              'backgroundHex': '#FFFFFF',
              'textColorHex': '#FF6500',
              'fontSize': 11.0,
              'fontWeight': 'w900',
              'borderRadius': 999.0,
              'label': '− 1 +',
            },
          ),
          MBAdvancedElementVariant(
            id: 'quantity_chip',
            groupId: 'quantity',
            elementType: 'quantity',
            title: 'Qty chip',
            description: 'Simple qty chip',
            binding: 'static.quantity',
            defaultPosition: MBAdvancedDesignNodePosition(x: 0.64, y: 0.88, z: 43),
            defaultSize: MBAdvancedDesignNodeSize(width: 64, height: 28),
            defaultStyle: <String, dynamic>{
              'backgroundHex': '#FFFFFF',
              'textColorHex': '#FF6500',
              'fontSize': 11.0,
              'fontWeight': 'w900',
              'borderRadius': 999.0,
              'label': 'Qty 1',
            },
          ),
        ],
      ),
      MBAdvancedElementGroup(
        id: 'divider',
        title: 'Divider',
        subtitle: 'Line and separator elements',
        variants: <MBAdvancedElementVariant>[
          MBAdvancedElementVariant(
            id: 'divider_line',
            groupId: 'divider',
            elementType: 'divider',
            title: 'Line divider',
            description: 'Horizontal separator',
            binding: 'static.divider',
            defaultPosition: MBAdvancedDesignNodePosition(x: 0.50, y: 0.72, z: 18),
            defaultSize: MBAdvancedDesignNodeSize(width: 180, height: 2),
            defaultStyle: <String, dynamic>{
              'backgroundHex': '#FFFFFF',
              'opacity': 0.7,
            },
          ),
          MBAdvancedElementVariant(
            id: 'divider_soft',
            groupId: 'divider',
            elementType: 'divider',
            title: 'Soft divider',
            description: 'Soft separator',
            binding: 'static.divider',
            defaultPosition: MBAdvancedDesignNodePosition(x: 0.50, y: 0.72, z: 18),
            defaultSize: MBAdvancedDesignNodeSize(width: 180, height: 6),
            defaultStyle: <String, dynamic>{
              'backgroundHex': '#FFFFFF',
              'opacity': 0.22,
              'borderRadius': 999.0,
            },
          ),
        ],
      ),
      MBAdvancedElementGroup(
        id: 'shape',
        title: 'Shape',
        subtitle: 'Decorative blocks and circles',
        variants: <MBAdvancedElementVariant>[
          MBAdvancedElementVariant(
            id: 'shape_circle',
            groupId: 'shape',
            elementType: 'shape',
            title: 'Circle',
            description: 'Decorative circle',
            binding: 'static.shape',
            defaultPosition: MBAdvancedDesignNodePosition(x: 0.78, y: 0.18, z: 8),
            defaultSize: MBAdvancedDesignNodeSize(width: 84, height: 84),
            defaultStyle: <String, dynamic>{
              'backgroundHex': '#FFB25E',
              'opacity': 0.45,
              'borderRadius': 999.0,
            },
          ),
          MBAdvancedElementVariant(
            id: 'shape_blob',
            groupId: 'shape',
            elementType: 'shape',
            title: 'Rounded blob',
            description: 'Decorative blob',
            binding: 'static.shape',
            defaultPosition: MBAdvancedDesignNodePosition(x: 0.16, y: 0.64, z: 8),
            defaultSize: MBAdvancedDesignNodeSize(width: 90, height: 54),
            defaultStyle: <String, dynamic>{
              'backgroundHex': '#FFE3C8',
              'opacity': 0.8,
              'borderRadius': 999.0,
            },
          ),
        ],
      ),
    ];
  }
}
