// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkbMfx5eBScnS7JGPG_Su5PrzEr4HykOo',
    appId: '1:792554914631:web:f487875a5395cfaf4dc262',
    messagingSenderId: '792554914631',
    projectId: 'mutho-bazar',
    authDomain: 'mutho-bazar.firebaseapp.com',
    storageBucket: 'mutho-bazar.firebasestorage.app',
    measurementId: 'G-H62ZCVPMZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAySDj3NOfk1qkdj8iu-pTa_b71zOd86n8',
    appId: '1:792554914631:android:b0f5c7310325f3204dc262',
    messagingSenderId: '792554914631',
    projectId: 'mutho-bazar',
    storageBucket: 'mutho-bazar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjjltZnynidhJgsj8OUQaN2D0W_wUTlVA',
    appId: '1:792554914631:ios:406974cc9b697d224dc262',
    messagingSenderId: '792554914631',
    projectId: 'mutho-bazar',
    storageBucket: 'mutho-bazar.firebasestorage.app',
    iosBundleId: 'com.example.muthobazar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjjltZnynidhJgsj8OUQaN2D0W_wUTlVA',
    appId: '1:792554914631:ios:406974cc9b697d224dc262',
    messagingSenderId: '792554914631',
    projectId: 'mutho-bazar',
    storageBucket: 'mutho-bazar.firebasestorage.app',
    iosBundleId: 'com.example.muthobazar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkbMfx5eBScnS7JGPG_Su5PrzEr4HykOo',
    appId: '1:792554914631:web:b90c1f852528578e4dc262',
    messagingSenderId: '792554914631',
    projectId: 'mutho-bazar',
    authDomain: 'mutho-bazar.firebaseapp.com',
    storageBucket: 'mutho-bazar.firebasestorage.app',
    measurementId: 'G-GQ4MWQP7BQ',
  );

}
















